CREATE TABLE IF NOT EXISTS Users (
    UID SERIAL PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Email VARCHAR(255),
        PinHash TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Users
ADD COLUMN IF NOT EXISTS PinHash TEXT;

CREATE TABLE IF NOT EXISTS Games (
    GID SERIAL PRIMARY KEY,
    GameTime TIMESTAMP NOT NULL,
    Location VARCHAR(255),
    Status VARCHAR(20) DEFAULT 'scheduled' CHECK (Status IN ('scheduled', 'completed')),
    Type TEXT,
    CreatedBy TEXT
);

CREATE TABLE IF NOT EXISTS GamePlayers (
    GID INTEGER REFERENCES Games(GID) ON DELETE CASCADE,
    UID INTEGER REFERENCES Users(UID) ON DELETE CASCADE,
    Team INTEGER,
    Score INTEGER,
    IsWinner BOOLEAN,
    PRIMARY KEY (GID, UID)
);

CREATE TABLE IF NOT EXISTS SubGames (
    SGID SERIAL PRIMARY KEY,
    GID INTEGER NOT NULL REFERENCES Games(GID) ON DELETE CASCADE,
    Team1Score INTEGER,
    Team2Score INTEGER,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SubGamePlayers (
    SGID INTEGER REFERENCES SubGames(SGID) ON DELETE CASCADE,
    UID INTEGER REFERENCES Users(UID) ON DELETE CASCADE,
    Team INTEGER,
    IsWinner BOOLEAN,
    PRIMARY KEY (SGID, UID)
);

CREATE TABLE IF NOT EXISTS Conversations (
    CID SERIAL PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ConversationParticipants (
    CID INTEGER REFERENCES Conversations(CID),
    UID INTEGER REFERENCES Users(UID),
    PRIMARY KEY (CID, UID)
);

CREATE TABLE IF NOT EXISTS Messages (
    MessageID SERIAL PRIMARY KEY,
    CID INTEGER NOT NULL REFERENCES Conversations(CID),
    SenderUID INTEGER NOT NULL REFERENCES Users(UID),
    Content TEXT NOT NULL,
    SentAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
